apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collabboard-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/websocket-services: collabboard-web
spec:
  ingressClassName: nginx
  rules:
    - host: collabboard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: collabboard-web
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: collabboard-api
                port:
                  number: 4000
